In [2]:
# open BH file
# create data csv with down selected reactants
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('real_datasets/buchwald-hartwig.csv')
cond_titles = ['Catalyst','Solvent','Base']
reactant_titles = ['Amine','Bromide']
unique_rs = [data[r_title].unique() for r_title in reactant_titles]
unique_conds = [data[cond_title].unique() for cond_title in cond_titles]
titles = cond_titles + reactant_titles


In [4]:
unique_conds

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17, 18,
        19, 20, 21]),
 array([1, 2, 3]),
 array(['a', 'b', 'c'], dtype=object)]

In [8]:
unique_rs

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])]

In [19]:
r1 = np.random.choice(unique_rs[0], 25, replace=False)
r2 = np.random.choice(unique_rs[1], 25, replace=False)

In [20]:
r1.sort()
r2.sort()

In [21]:
r2

array([ 2,  3,  5,  9, 12, 13, 14, 16, 17, 18, 19, 20, 23, 25, 28, 29, 32,
       33, 34, 35, 36, 37, 41, 44, 48])

In [22]:
r1

array([ 3,  6, 12, 14, 15, 17, 18, 19, 20, 21, 22, 24, 26, 29, 31, 32, 33,
       37, 39, 42, 44, 46, 47, 48, 50])

In [23]:
pd_r_subset = data.loc[data['Amine'].isin(r1) & data['Bromide'].isin(r2)]

In [24]:
pd_r_subset

Amine  Bromide  Catalyst  Solvent Base      yield
18180       3        2         1        1    a  51.936035
18181       3        2         1        1    b  63.590748
18182       3        2         1        1    c   7.936288
18183       3        2         1        2    a  63.044823
18184       3        2         1        2    b  74.916670
...       ...      ...       ...      ...  ...        ...
449635     50       48        21        2    b  49.658880
449636     50       48        21        2    c   0.449201
449637     50       48        21        3    a   3.983429
449638     50       48        21        3    b  64.038760
449639     50       48        21        3    c   0.519896

[112500 rows x 6 columns]

In [25]:
pd_r_subset.to_csv('real_datasets/buchwald-hartwig_rxn_subset_1.csv', index=False)

In [28]:
len(unique_conds[0])

20

In [36]:
c1 = np.random.choice(unique_conds[0], 14, replace=False)
c2 = [1]
c3 = [1]

In [37]:
c1.sort()
c1

array([ 1,  2,  3,  4,  5,  6,  7,  9, 13, 14, 16, 18, 19, 20])

In [40]:
unique_conds

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17, 18,
        19, 20, 21]),
 array([1, 2, 3]),
 array(['a', 'b', 'c'], dtype=object)]

In [41]:
c2 = [2]
c3 = ['b']

In [42]:
pd_c_subset = data.loc[data['Catalyst'].isin(c1) & data['Base'].isin(c3) & data['Solvent'].isin(c2)]

In [43]:
pd_c_subset

Amine  Bromide  Catalyst  Solvent Base      yield
4           1        1         1        2    b   2.549122
13          1        1         2        2    b   2.080713
22          1        1         3        2    b  -0.447913
31          1        1         4        2    b   1.472128
40          1        1         5        2    b   0.279046
...       ...      ...       ...      ...  ...        ...
449941     50       50        14        2    b  18.077124
449950     50       50        16        2    b  12.807747
449968     50       50        18        2    b   9.830745
449977     50       50        19        2    b  19.725000
449986     50       50        20        2    b  53.420600

[35000 rows x 6 columns]

In [44]:
pd_c_subset.to_csv('real_datasets/buchwald-hartwig_cond_subset_1.csv', index=False)

In [45]:
pd_both_subset = data.loc[data['Catalyst'].isin(c1) & data['Base'].isin(c3) & data['Solvent'].isin(c2) & data['Amine'].isin(r1) & data['Bromide'].isin(r2)]

In [46]:
pd_both_subset

Amine  Bromide  Catalyst  Solvent Base      yield
18184       3        2         1        2    b  74.916670
18193       3        2         2        2    b  91.927140
18202       3        2         3        2    b  19.529602
18211       3        2         4        2    b  40.366356
18220       3        2         5        2    b  58.260160
...       ...      ...       ...      ...  ...        ...
449581     50       48        14        2    b   4.134604
449590     50       48        16        2    b  10.804010
449608     50       48        18        2    b   7.800378
449617     50       48        19        2    b  16.522871
449626     50       48        20        2    b  53.394140

[8750 rows x 6 columns]

In [47]:
pd_both_subset.to_csv('real_datasets/buchwald-hartwig_both_subset_1.csv', index=False)